<?php

namespace Database\Seeders;
use App\Models\Marca;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MarcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Marca::factory(10)->create();
        $carBrands = [
            "Acura",
            "Alfa Romeo",
            "Alpine",
            "Aramis",
            "Ariel",
            "Aston Martin",
            "Audi",
            "Automobili Pininfarina",
            "BAC",
            "Bentley",
            "Bera",
            "BRZ",
            "BMW",
            "Brilliance",
            "Bugatti",
            "Buick",
            "BYD",
            "Cadillac",
            "Campagnola",
            "Carver",
            "Caterham",
            "Chevrolet",
            "Chrysler",
            "Citroën",
            "Coda",
            "Corvette",
            "Dacia",
            "Daihatsu",
            "DeLorean",
            "Dodge",
            "DS",
            "Eagle",
            "Edsel",
            "Empire",
            "Fiat",
            "Fisker",
            "Ford",
            "Foton",
            "GAC",
            "Genesis",
            "Geo",
            "GMC",
            "Great Wall",
            "Hafei",
            "Haval",
            "Healey",
            "Hennessey",
            "Hillman",
            "Holden",
            "Honda",
            "Hornet",
            "Hudson",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Isuzu",
            "JAC",
            "Jaguar",
            "Jeep",
            "Karma",
            "Kia",
            "Koenigsegg",
            "KTM",
            "LADA",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Lexus",
            "Lifan",
            "Lincoln",
            "Lister",
            "Lotus",
            "Lucid",
            "Luxgen",
            "Mahindra",
            "Maserati",
            "Maybach",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mercury",
            "MG",
            "Microcar",
            "Mini",
            "Mitsubishi",
            "Morgan",
            "Morris",
            "Nissan",
            "Noble",
            "Opel",
            "Pagani",
            "Peugeot",
            "Pininfarina",
            "Pontiac",
            "Porsche",
            "Proton",
            "Puritalia",
            "Qvale",
            "Ram",
            "Renault",
            "Rimac",
            "Rivian",
            "Rolls-Royce",
            "Rover",
            "SAAB",
            "Saleen",
            "Samsung",
            "Škoda",
            "Smart",
            "Spyker",
            "SsangYong",
            "Subaru",
            "Suzuki",
            "Tesla",
            "Toyota",
            "Tramontana",
            "TVR",
            "Venturi",
            "Volkswagen",
            "Volvo",
            "W Motors",
            "Wartburg",
            "Westfield",
            "Willys",
            "Xin Kai",
            "XPeng",
            "Yema",
            "Yugo",
            "ZAGATO",
            "Zenvo",
        ];
       
        foreach ($carBrands as $carBrand) {
            Marca::create([
                'descripcion' => $carBrand,                
            ]);            
            
        }
    }
}
